steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/approvalpakuwon', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/approvalpakuwon']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'approvalpakuwon',
        '--image',
        'gcr.io/$PROJECT_ID/approvalpakuwon',
        '--region',
        'asia-southeast2',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/approvalpakuwon'
